name: angular_quill_example
description: Quill example
version: 0.0.3
homepage: https://github.com/adamlofts/angular_quill
author: Adam Lofts <adam.lofts@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.0.0
  angular_quill:
    git:
      url: https://github.com/adamlofts/angular_quill.git
      ref: master

dev_dependencies:
  build_runner: ^1.6.5
  build_test: ^0.10.3+1
  build_web_compilers: ^2.9.0
  test: ^1.12.0
  webdev:
