name: angular_quill_example
description: Quill example
version: 0.0.3
homepage: https://github.com/adamlofts/angular_quill

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_quill: ^0.2.0

dev_dependencies:
  build_runner:
  build_web_compilers:
  test:
  webdev:
