name: angular_quill_example
description: Quill example
version: 0.0.1
homepage: https://github.com/adamlofts/angular_quill
author: Adam Lofts <adam.lofts@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  angular_quill: ^0.0.4

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
